#?  'PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION' se establece en 'false' para deshabilitar la protección de cookies mejorada.
#? 'value: "false"' indica que el valor de la variable de entorno es 'false'.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-admin-deployment
  labels:
    app: pg-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      containers:
      - name: pg-admin
        image: dpage/pgadmin4:6.17
        ports:
        - containerPort: 80
        env:
          - name: PGADMIN_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-admin-secrets
                key: DB_PASSWORD
          - name: PGADMIN_DEFAULT_EMAIL
            valueFrom:
              secretKeyRef:
                name: pg-admin-secrets
                key: PG_USER_EMAIL
          - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
            value: "False"
---

#? 'type' es el tipo de recurso que se creará. En este caso, un Service que se usará para acceder a pgAdmin.
#? 'type: NodePort' indica que el Service se expondrá en un puerto específico en cada nodo del clúster. 
#? NodePort es un tipo de Service que se usa para acceder a los Pods desde fuera del clúster.

#? 'nodePort' es el puerto que se expondrá en cada nodo del clúster. El puerto debe estar en el rango de 
#? puertos permitidos por Kubernetes, que es de 30000 a 32767.

apiVersion: v1
kind: Service
metadata:
  name: pg-admin-service
spec:
  type: NodePort
  selector:
    app: pg-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30200