#? 'kind' es el tipo de recurso que se creará. En este caso, un Secret que se usará para almacenar información sensible.
#? 'name' es el nombre del Secret. Se usará para identificar el recurso.
#? 'type' es el tipo de Secret. En este caso, Opaque indica que el Secret no se codificará en base64.

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # postgres 
  DB_USER: cG9zdGdyZXM=
  # EstoEsUnPasswordSecreto
  DB_PASSWORD: RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=