#? 'apiVersion' es la versión de la API de Kubernetes que se usará para crear el recurso.
#? 'kind' es el tipo de recurso que se creará.En este caso, un ConfigMap que se usará para almacenar la configuración de PostgreSQL.
#? 'metadata' es un objeto que contiene metadatos adicionales para el recurso.
#?   'name' es el nombre del ConfigMap. Se usará para identificar el recurso.
#? 'data' es un objeto que contiene los datos que se almacenarán en el ConfigMap.
#?   DB_NAME es el nombre de la base de datos que se creará en PostgreSQL.
#?   DB_HOST es el nombre del servicio de Kubernetes que se usará para acceder a la base de datos.
#?   DB_PORT es el puerto en el que se ejecutará PostgreSQL. Por defecto, es 5432.


apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  DB_NAME: postgres
  DB_HOST: postgres-service
  DB_PORT: "5432"
  
